apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: argocd
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: 8.0.12
    helm:
      valueFiles:
      - $values/infra/argocd/values.yaml
  - repoURL: 'https://github.com/tatsukoni-pra/k8s-demo'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/tatsukoni-pra/k8s-demo'
    path: infra/argocd
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
