apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlantis-vcs-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: github_secret
      remoteRef:
        key: eks-test-cluster/atlantis/secret
        property: github-webhook-secret
    - secretKey: key.pem
      remoteRef:
        key: eks-test-cluster/atlantis/secret
        property: github-app-privateKey
