atlantisUrl: "https://atlantis.awsometatsukoni.com/"

orgAllowlist: "github.com/tatsukoni-pra/*"

logLevel: "debug"

githubApp:
  id: "4789286"
  installationId: "158140158"
  slug: atlantis-tatsukoni-pra

vcsSecretName: "atlantis-vcs-secret"

image:
  repository: ghcr.io/runatlantis/atlantis
  tag: "v0.42.0"
  pullPolicy: IfNotPresent

config: |
  ---
  automerge: true
  allow-fork-prs: false
  disable-apply-all: false
  hide-prev-plan-comments: true
  enable-policy-checks: false
  allow-commands: all
  write-git-creds: true
  emoji-reaction: eyes

repoConfig: |
  ---
  repos:
  - id: /.*/
    apply_requirements: [mergeable]
    workflow: default
    allowed_overrides: [workflow]
    allow_custom_workflows: true
  workflows:
    default:
      plan:
        steps:
          - init
          - plan
          - show
      apply:
        steps:
          - run: |
              echo "Execute Apply"
          - apply

serviceAccount:
  create: false
  name: sa-atlantis

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

test:
  enabled: false

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m

nodeSelector: {}

tolerations: []

volumeClaim:
  dataStorage: 10Gi
  storageClassName: "gp2"
