apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: atlantis
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: atlantis
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
