apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd-image-updater
  source:
    repoURL: https://github.com/tatsukoni-pra/k8s-demo
    path: infra/argocd-image-updater
    targetRevision: main
