apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
spec:
  project: argocd-image-updater
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argocd-image-updater
    targetRevision: 0.12.3

    helm:
      valueFiles:
      - $values/infra/argocd-image-updater/values.yaml
  - repoURL: 'https://github.com/tatsukoni-pra/k8s-demo'
    targetRevision: main
    ref: values
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
