apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-application-nginx-deployment
  labels:
    app: k8s-application
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: k8s-application
  template:
    metadata:
      labels:
        app: k8s-application
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: k8s-application-nginx
        image: k8s-application-nginx-image
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: APP
          value: "web"
        - name: ENVIRONMENT
          value: "test"
        # Kubernetes Secretから環境変数を設定
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-application-secret # Kubernetes Secret Name
              key: DB_PASSWORD # Kubernetes Secret Key
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: k8s-application-secret
              key: DB_USER
