apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-application-secret
spec:
  # 外部providerに対してデータ参照を行いSecretの値を更新する頻度
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    # `kind: Secret` として作成されたリソースの名前であり、無指定の場合には `.metadata.name` が指定される。
    # name: github-repo-secret
    # `Owner`, `Merge`, `None` から指定する。デフォルトは `Owner`
    # `Owner` は Secretリソースを作成し、 `.metadata.ownerReferences` をセットする。
    # `Merge` は Secretリソースを作成しないが `.spec.data` の値をSecretリソースに反映させる
    # `None` は Secretリソースを作成しない（将来的にはinjectorとして利用可能になる想定）
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: eks-test-cluster/k8s-application/secret #AWS Secrets Manager secret name
      property: DB_USER #AWS Secrets Manager secret key
  - secretKey: DB_PASSWORD
    remoteRef:
      key: eks-test-cluster/k8s-application/secret #AWS Secrets Manager secret name
      property: DB_PASSWORD #AWS Secrets Manager secret key
