apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: k8s-application-tgb
spec:
  serviceRef:
    name: k8s-application-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-1:083636136646:targetgroup/tg-k8s-application/08a277ba1fc98e47
  targetType: ip
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: sg-09404dd1f6df8c55a
      ports:
      - protocol: TCP
        port: 80
