apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  log.level: debug
  # echo "AWS:$(aws ecr get-login-password --region ap-northeast-1)"
  ecr-login.sh: |
    #!/bin/sh
    HOME=/tmp aws ecr --region ap-northeast-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
  registries.conf: |
    registries:
      - name: ECR
        api_url: https://083636136646.dkr.ecr.ap-northeast-1.amazonaws.com
        prefix: 083636136646.dkr.ecr.ap-northeast-1.amazonaws.com
        credentials: ext:/app/scripts/ecr-login.sh
        credsexpire: 10h
        default: true
        insecure: no
        ping: yes
