# https://github.com/argoproj/argo-helm/tree/main/charts/argocd-image-updater
# https://github.com/argoproj-labs/argocd-image-updater/issues/112#issuecomment-2235983279
extraEnv:
  - name: AWS_REGION
    value: "ap-northeast-1"

config:
  applicationsAPIKind: "kubernetes"
  logLevel: "debug"

  registries:
  - name: ECR
    api_url: https://083636136646.dkr.ecr.ap-northeast-1.amazonaws.com
    prefix: 083636136646.dkr.ecr.ap-northeast-1.amazonaws.com
    default: true
    ping: yes
    insecure: no
    credentials: ext:/scripts/ecr-login.sh
    credsexpire: 10h

authScripts:
  enabled: true
  scripts:
    # https://github.com/argoproj-labs/argocd-image-updater/issues/720#issuecomment-2190747070
    ecr-login.sh: |
      #!/bin/sh
      HOME=/tmp aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::083636136646:role/argocd-image-updater
  name: "argocd-image-updater"

securityContext:
  readOnlyRootFilesystem: false
