extraEnv:
  - name: AWS_REGION
    value: "ap-northeast-1"

config:
  applicationsAPIKind: "kubernetes"
  logLevel: "debug"

  registries:
  - name: ECR
    api_url: https://083636136646.dkr.ecr.us-east-1.amazonaws.com
    prefix: 083636136646.dkr.ecr.us-east-1.amazonaws.com
    default: true
    ping: yes
    insecure: no
    credentials: ext:/scripts/ecr-login.sh
    credsexpire: 10h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      aws ecr --region ap-northeast-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

serviceAccount:
  create: false
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::083636136646:role/argocd-image-updater
  name: "argocd-image-updater"

securityContext:
  readOnlyRootFilesystem: false
