apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo-secret
  # `labels` と `annotations` は作成されるSecretにも引き継がれる
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  # 外部providerに対してデータ参照を行いSecretの値を更新する頻度
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    # `kind: Secret` として作成されたリソースの名前であり、無指定の場合には `.metadata.name` が指定される。
    # name: github-repo-secret
    # `Owner`, `Merge`, `None` から指定する。デフォルトは `Owner`
    # `Owner` は Secretリソースを作成し、 `.metadata.ownerReferences` をセットする。
    # `Merge` は Secretリソースを作成しないが `.spec.data` の値をSecretリソースに反映させる
    # `None` は Secretリソースを作成しない（将来的にはinjectorとして利用可能になる想定）
    creationPolicy: Owner
  data:
  - secretKey: githubAppID
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: github-app-client-id #AWS Secrets Manager secret key
  - secretKey: githubAppInstallationID
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: github-app-installation-id #AWS Secrets Manager secret key
  - secretKey: githubAppPrivateKey
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: github-app-privateKey #AWS Secrets Manager secret key
  - secretKey: url
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: url #AWS Secrets Manager secret key
  - secretKey: type
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: type #AWS Secrets Manager secret key
