apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-repo-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: repo-2327254488
    creationPolicy: Owner
  data:
  - secretKey: githubAppID
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: github-app-id #AWS Secrets Manager secret key
  - secretKey: githubAppInstallationID
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: github-app-installation-id #AWS Secrets Manager secret key
  - secretKey: githubAppPrivateKey
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: github-app-private-key #AWS Secrets Manager secret key
  - secretKey: url
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: url #AWS Secrets Manager secret key
  - secretKey: type
    remoteRef:
      key: eks-test-cluster/argocd/secret #AWS Secrets Manager secret name
      property: type #AWS Secrets Manager secret key
